version: 0.2

phases:
  install:
    commands:
      - echo installing terrafrom
      - "apt install unzip -y"
      - "wget https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip"
      - "unzip terraform_1.0.5_linux_amd64.zip"
      - "mv terraform /usr/local/bin/"
  pre_build:
    commands:
      - terraform init
      - terraform plan -lock=false
  build:
    commands:
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo terraform terraform plan completed on 'date'
