---
version: 0.2
phases:
  install:
    commands:
      - BUCKET_EXISTS=$(aws s3api head-bucket --bucket rajeshsamudu2520 2>&1 ||
        true)
      - >
        if [ -z "$BUCKET_EXISTS" ]; then 
          echo "Bucket exists-not creating"
        else 
          echo "Bucket does not exist crating the bucket" 
          aws s3api create-bucket --bucket tf-state-kinetic-$APP_ENV --region ap-south-1 --create-bucket-configuration fi LocationConstraint=ap-southeast-1 || true
        fi
      - echo installing terrafrom
      - apt install unzip -y
      - wget
        https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip
      - unzip terraform_1.0.5_linux_amd64.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - terraform init
      - terraform plan -lock=false
  build:
    commands:
      - terraform apply -auto-approve -lock=false
  post_build:
    commands:
      - echo terraform terraform plan completed on 'date'
